import json
import re
import requests
from functools import lru_cache
import os
os.environ.pop("SSLKEYLOGFILE", None)

NAME_ALIASES = {
    "Kangaskham": "kangaskhan-mega",
    "Lopunnym": "lopunny-mega",
    "Pidgeotm": "pidgeot-mega",
    "Audinom": "audino-mega",
    "Mawilem": "mawile-mega",
    "Growlitheh": "growlithe-hisui",
    "Zoroarkh": "zoroark-hisui",
    "Braviaryh": "braviary-hisui",
    "Electrodeh": "electrode-hisui",
    "Dudunsprce": "dudunsparce",
    "Squawkbily": "squawkabilly",
    "Miniorc": "minior-core",
    "Golema": "golem-alola",
  "Abomasnow": "abomasnow",
  "Abomasnowm": "abomasnow-mega",
  "Abra": "abra",
  "Absol": "absol",
  "Absolm": "absol-mega",
  "Accelgor": "accelgor",
  "Aerodactyl": "aerodactyl",
  "Aggron": "aggron",
  "Aipom": "aipom",
  "Alakazam": "alakazam",
  "Alakazamm": "alakazam-mega",
  "Alcremie": "alcremie",
  "Alomomola": "alomomola",
  "Altaria": "altaria",
  "Altariam": "altaria-mega",
  "Amaura": "amaura",
  "Ambipom": "ambipom",
  "Amoonguss": "amoonguss",
  "Ampharos": "ampharos",
  "Annihilape": "annihilape",
  "Anorith": "anorith",
  "Appletun": "appletun",
  "Applin": "applin",
  "Araquanid": "araquanid",
  "Arbok": "arbok",
  "Arboliva": "arboliva",
  "Arcanine": "arcanine",
  "Arcanineh": "arcanine-hisui",
  "Archaludon": "archaludon",
  "Archen": "archen",
  "Archeops": "archeops",
  "Arctibax": "arctibax",
  "Arctovish": "arctovish",
  "Arctozolt": "arctozolt",
  "Ariados": "ariados",
  "Armaldo": "armaldo",
  "Armarouge": "armarouge",
  "Aromatisse": "aromatisse",
  "Aron": "aron",
  "Arrokuda": "arrokuda",
  "Articuno": "articuno",
  "Articunog": "articuno-galar",
  "Audino": "audino",
  "Audinom": "audino-mega",
  "Aurorus": "aurorus",
  "Avalugg": "avalugg",
  "Avaluggh": "avalugg-hisui",
  "Axew": "axew",
  "Azelf": "azelf",
  "Azumarill": "azumarill",
  "Azurill": "azurill",
  "Bagon": "bagon",
  "Baltoy": "baltoy",
  "Banette": "banette",
  "Banettem": "banette-mega",
  "Barbaracle": "barbaracle",
  "Barboach": "barboach",
  "Bastiodon": "bastiodon",
  "Baxcalibur": "baxcalibur",
  "Bayleef": "bayleef",
  "Beartic": "beartic",
  "Beautifly": "beautifly",
  "Beedrill": "beedrill",
  "Beedrillm": "beedrill-mega",
  "Beheeyem": "beheeyem",
  "Beldum": "beldum",
  "Bellibolt": "bellibolt",
  "Bellossom": "bellossom",
  "Bellsprout": "bellsprout",
  "Bergmite": "bergmite",
  "Bewear": "bewear",
  "Bibarel": "bibarel",
  "Bidoof": "bidoof",
  "Binacle": "binacle",
  "Bisharp": "bisharp",
  "Blastoise": "blastoise",
  "Blaziken": "blaziken",
  "Blipbug": "blipbug",
  "Blissey": "blissey",
  "Blitzle": "blitzle",
  "Boldore": "boldore",
  "Boltund": "boltund",
  "Bombirdier": "bombirdier",
  "Bonsly": "bonsly",
  "Bouffalant": "bouffalant",
  "Bounsweet": "bounsweet",
  "Braixen": "braixen",
  "Bramblin": "bramblin",
  "Braviary": "braviary",
  "Braviaryh": "braviary-hisui",
  "Breloom": "breloom",
  "Brionne": "brionne",
  "Bronzong": "bronzong",
  "Bronzor": "bronzor",
  "Bruxish": "bruxish",
  "Budew": "budew",
  "Buizel": "buizel",
  "Bulbasaur": "bulbasaur",
  "Buneary": "buneary",
  "Bunnelby": "bunnelby",
  "Burmy": "burmy",
  "Butterfree": "butterfree",
  "Buzzwole": "buzzwole",
  "Cacnea": "cacnea",
  "Cacturne": "cacturne",
  "Calyrex": "calyrex",
  "Camerupt": "camerupt",
  "Cameruptm": "camerupt-mega",
  "Capsakid": "capsakid",
  "Carbink": "carbink",
  "Carkol": "carkol",
  "Carnivine": "carnivine",
  "Carracosta": "carracosta",
  "Carvanha": "carvanha",
  "Cascoon": "cascoon",
  "Castform": "castform",
  "Caterpie": "caterpie",
  "Celebi": "celebi",
  "Celesteela": "celesteela",
  "Ceruledge": "ceruledge",
  "Cetitan": "cetitan",
  "Cetoddle": "cetoddle",
  "Chandelure": "chandelure",
  "Chansey": "chansey",
  "Charcadet": "charcadet",
  "Charizard": "charizard",
  "Charjabug": "charjabug",
  "Charmander": "charmander",
  "Charmeleon": "charmeleon",
  "Chatot": "chatot",
  "Cherrim": "cherrim",
  "Cherubi": "cherubi",
  "Chesnaught": "chesnaught",
  "Chespin": "chespin",
  "Chewtle": "chewtle",
  "Chi-Yu": "chi-yu",
  "Chien-Pao": "chien-pao",
  "Chikorita": "chikorita",
  "Chimchar": "chimchar",
  "Chimecho": "chimecho",
  "Chinchou": "chinchou",
  "Chingling": "chingling",
  "Cinccino": "cinccino",
  "Cinderace": "cinderace",
  "Clamperl": "clamperl",
  "Clauncher": "clauncher",
  "Clawitzer": "clawitzer",
  "Claydol": "claydol",
  "Clefable": "clefable",
  "Clefairy": "clefairy",
  "Cleffa": "cleffa",
  "Clobbopus": "clobbopus",
  "Clodsire": "clodsire",
  "Cloyster": "cloyster",
  "Coalossal": "coalossal",
  "Cobalion": "cobalion",
  "Cofagrigus": "cofagrigus",
  "Combee": "combee",
  "Combusken": "combusken",
  "Comfey": "comfey",
  "Conkeldurr": "conkeldurr",
  "Copperajah": "copperajah",
  "Corphish": "corphish",
  "Corsola": "corsola",
  "Corsolag": "corsola-galar",
  "Cosmoem": "cosmoem",
  "Cosmog": "cosmog",
  "Cottonee": "cottonee",
  "Crabrawler": "crabrawler",
  "Cradily": "cradily",
  "Cramorant": "cramorant",
  "Cranidos": "cranidos",
  "Crawdaunt": "crawdaunt",
  "Cresselia": "cresselia",
  "Croagunk": "croagunk",
  "Crobat": "crobat",
  "Crocalor": "crocalor",
  "Croconaw": "croconaw",
  "Crustle": "crustle",
  "Cryogonal": "cryogonal",
  "Cubchoo": "cubchoo",
  "Cubone": "cubone",
  "Cufant": "cufant",
  "Cursola": "cursola",
  "Cutiefly": "cutiefly",
  "Cyclizar": "cyclizar",
  "Cyndaquil": "cyndaquil",
  "Dachsbun": "dachsbun",
  "Darkrai": "darkrai",
  "Dartrix": "dartrix",
  "Darumaka": "darumaka",
  "Darumakag": "darumaka-galar",
  "Decidueye": "decidueye",
  "Decidueyeh": "decidueye-hisui",
  "Dedenne": "dedenne",
  "Deerling": "deerling",
  "Deino": "deino",
  "Delcatty": "delcatty",
  "Delibird": "delibird",
  "Delphox": "delphox",
  "Dewgong": "dewgong",
  "Dewott": "dewott",
  "Dewpider": "dewpider",
  "Dhelmise": "dhelmise",
  "Diancie": "diancie",
  "Diggersby": "diggersby",
  "Diglett": "diglett",
  "Dipplin": "dipplin",
  "Ditto": "ditto",
  "Dodrio": "dodrio",
  "Doduo": "doduo",
  "Dolliv": "dolliv",
  "Dondozo": "dondozo",
  "Donphan": "donphan",
  "Dottler": "dottler",
  "Doublade": "doublade",
  "Dracovish": "dracovish",
  "Dracozolt": "dracozolt",
  "Dragalge": "dragalge",
  "Dragapult": "dragapult",
  "Dragonair": "dragonair",
  "Dragonite": "dragonite",
  "Drakloak": "drakloak",
  "Drampa": "drampa",
  "Drapion": "drapion",
  "Dratini": "dratini",
  "Drednaw": "drednaw",
  "Dreepy": "dreepy",
  "Drifblim": "drifblim",
  "Drifloon": "drifloon",
  "Drilbur": "drilbur",
  "Drizzile": "drizzile",
  "Drowzee": "drowzee",
  "Druddigon": "druddigon",
  "Dubwool": "dubwool",
  "Ducklett": "ducklett",
  "Dugtrio": "dugtrio",
  "Dunsparce": "dunsparce",
  "Duosion": "duosion",
  "Duraludon": "duraludon",
  "Durant": "durant",
  "Dusclops": "dusclops",
  "Dusknoir": "dusknoir",
  "Duskull": "duskull",
  "Dustox": "dustox",
  "Dwebble": "dwebble",
  "Eelektrik": "eelektrik",
  "Eelektross": "eelektross",
  "Eevee": "eevee",
  "Ekans": "ekans",
  "Eldegoss": "eldegoss",
  "Electabuzz": "electabuzz",
  "Electivire": "electivire",
  "Electrike": "electrike",
  "Electrode": "electrode",
  "Electrodeh": "electrode-hisui",
  "Elekid": "elekid",
  "Elgyem": "elgyem",
  "Emboar": "emboar",
  "Emolga": "emolga",
  "Empoleon": "empoleon",
  "Enamorus": "enamorus-therian",
  "Entei": "entei",
  "Escavalier": "escavalier",
  "Espathra": "espathra",
  "Espeon": "espeon",
  "Espurr": "espurr",
  "Excadrill": "excadrill",
  "Exeggcute": "exeggcute",
  "Exeggutor": "exeggutor",
  "Exploud": "exploud",
  "Falinks": "falinks",
  "Farfetchdg": "farfetchd-galar",
  "Farfetch’d": "farfetchd",
  "Farigiraf": "farigiraf",
  "Fearow": "fearow",
  "Feebas": "feebas",
  "Fennekin": "fennekin",
  "Feraligatr": "feraligatr",
  "Ferroseed": "ferroseed",
  "Ferrothorn": "ferrothorn",
  "Fidough": "fidough",
  "Finizen": "finizen",
  "Finneon": "finneon",
  "Flaaffy": "flaaffy",
  "Flamigo": "flamigo",
  "Flapple": "flapple",
  "Flareon": "flareon",
  "Fletchling": "fletchling",
  "Flittle": "flittle",
  "Floatzel": "floatzel",
  "Floette": "floette",
  "Floragato": "floragato",
  "Florges": "florges",
  "Flygon": "flygon",
  "Fomantis": "fomantis",
  "Foongus": "foongus",
  "Forretress": "forretress",
  "Fraxure": "fraxure",
  "Frigibax": "frigibax",
  "Frillish": "frillish",
  "Froakie": "froakie",
  "Frogadier": "frogadier",
  "Froslass": "froslass",
  "Frosmoth": "frosmoth",
  "Fuecoco": "fuecoco",
  "Furfrou": "furfrou",
  "Furret": "furret",
  "Gabite": "gabite",
  "Gallade": "gallade",
  "Galvantula": "galvantula",
  "Garbodor": "garbodor",
  "Garchomp": "garchomp",
  "Gardevoir": "gardevoir",
  "Garganacl": "garganacl",
  "Gastly": "gastly",
  "Gastrodon": "gastrodon",
  "Genesect": "genesect",
  "Gengar": "gengar",
  "Gengarm": "gengar-mega",
  "Geodude": "geodude",
  "Gholdengo": "gholdengo",
  "Gible": "gible",
  "Gigalith": "gigalith",
  "Gimmighoul": "gimmighoul",
  "Girafarig": "girafarig",
  "Glaceon": "glaceon",
  "Glalie": "glalie",
  "Glaliem": "glalie-mega",
  "Glameow": "glameow",
  "Glastrier": "glastrier",
  "Gligar": "gligar",
  "Glimmet": "glimmet",
  "Glimmora": "glimmora",
  "Gliscor": "gliscor",
  "Gloom": "gloom",
  "Gogoat": "gogoat",
  "Golbat": "golbat",
  "Goldeen": "goldeen",
  "Golduck": "golduck",
  "Golem": "golem",
  "Golett": "golett",
  "Golisopod": "golisopod",
  "Golurk": "golurk",
  "Goodra": "goodra",
  "Goodrah": "goodra-hisui",
  "Goomy": "goomy",
  "Gorebyss": "gorebyss",
  "Gossifleur": "gossifleur",
  "Gothita": "gothita",
  "Gothitelle": "gothitelle",
  "Gothorita": "gothorita",
  "Grafaiai": "grafaiai",
  "Granbull": "granbull",
  "Grapploct": "grapploct",
  "Graveler": "graveler",
  "Great Tusk": "great-tusk",
  "Greavard": "greavard",
  "Greedent": "greedent",
  "Greninja": "greninja",
  "Grimer": "grimer",
  "Grimmsnarl": "grimmsnarl",
  "Grookey": "grookey",
  "Grotle": "grotle",
  "Grovyle": "grovyle",
  "Growlithe": "growlithe",
  "Growlitheh": "growlithe-hisui",
  "Grubbin": "grubbin",
  "Grumpig": "grumpig",
  "Gulpin": "gulpin",
  "Gumshoos": "gumshoos",
  "Gurdurr": "gurdurr",
  "Guzzlord": "guzzlord",
  "Gyarados": "gyarados",
  "Hakamo-O": "hakamo-o",
  "Happiny": "happiny",
  "Hariyama": "hariyama",
  "Hatenna": "hatenna",
  "Hatterene": "hatterene",
  "Hattrem": "hattrem",
  "Haunter": "haunter",
  "Hawlucha": "hawlucha",
  "Haxorus": "haxorus",
  "Heatmor": "heatmor",
  "Heatran": "heatran",
  "Heliolisk": "heliolisk",
  "Helioptile": "helioptile",
  "Heracross": "heracross",
  "Heracrossm": "heracross-mega",
  "Herdier": "herdier",
  "Hippopotas": "hippopotas",
  "Hippowdon": "hippowdon",
  "Hitmonchan": "hitmonchan",
  "Hitmonlee": "hitmonlee",
  "Hitmontop": "hitmontop",
  "Honchkrow": "honchkrow",
  "Honedge": "honedge",
  "Hoopa": "hoopa",
  "Hoothoot": "hoothoot",
  "Hoppip": "hoppip",
  "Horsea": "horsea",
  "Houndoom": "houndoom",
  "Houndoomm": "houndoom-mega",
  "Houndour": "houndour",
  "Houndstone": "houndstone",
  "Huntail": "huntail",
  "Hydrapple": "hydrapple",
  "Hydreigon": "hydreigon",
  "Hypno": "hypno",
  "Igglybuff": "igglybuff",
  "Illumise": "illumise",
  "Impidimp": "impidimp",
  "Incineroar": "incineroar",
  "Infernape": "infernape",
  "Inkay": "inkay",
  "Inteleon": "inteleon",
  "Iron Crown": "iron-crown",
  "Iron Hands": "iron-hands",
  "Iron Moth": "iron-moth",
  "Ivysaur": "ivysaur",
  "Jangmo-O": "jangmo-o",
  "Jellicent": "jellicent",
  "Jigglypuff": "jigglypuff",
  "Jirachi": "jirachi",
  "Jolteon": "jolteon",
  "Joltik": "joltik",
  "Jumpluff": "jumpluff",
  "Jynx": "jynx",
  "Kabuto": "kabuto",
  "Kabutops": "kabutops",
  "Kadabra": "kadabra",
  "Kakuna": "kakuna",
  "Kangaskhan": "kangaskhan",
  "Karrablast": "karrablast",
  "Kartana": "kartana",
  "Kecleon": "kecleon",
  "Kingambit": "kingambit",
  "Kingdra": "kingdra",
  "Kingler": "kingler",
  "Kirlia": "kirlia",
  "Klang": "klang",
  "Klawf": "klawf",
  "Kleavor": "kleavor",
  "Klefki": "klefki",
  "Klink": "klink",
  "Klinklang": "klinklang",
  "Koffing": "koffing",
  "Komala": "komala",
  "Kommo-O": "kommo-o",
  "Krabby": "krabby",
  "Kricketot": "kricketot",
  "Kricketune": "kricketune",
  "Krokorok": "krokorok",
  "Krookodile": "krookodile",
  "Kubfu": "kubfu",
  "Lairon": "lairon",
  "Lampent": "lampent",
  "Landorus": "landorus-therian",
  "Lanturn": "lanturn",
  "Lapras": "lapras",
  "Larvesta": "larvesta",
  "Larvitar": "larvitar",
  "Latias": "latias",
  "Latios": "latios",
  "Leafeon": "leafeon",
  "Leavanny": "leavanny",
  "Lechonk": "lechonk",
  "Ledian": "ledian",
  "Ledyba": "ledyba",
  "Lickilicky": "lickilicky",
  "Lickitung": "lickitung",
  "Liepard": "liepard",
  "Lileep": "lileep",
  "Lilligant": "lilligant",
  "Lilliganth": "lilligant-hisui",
  "Lillipup": "lillipup",
  "Linoone": "linoone",
  "Linooneg": "linoone-galar",
  "Litleo": "litleo",
  "Litten": "litten",
  "Litwick": "litwick",
  "Lokix": "lokix",
  "Lombre": "lombre",
  "Lopunny": "lopunny",
  "Lopunnym": "lopunny-mega",
  "Lotad": "lotad",
  "Loudred": "loudred",
  "Lucario": "lucario",
  "Ludicolo": "ludicolo",
  "Lumineon": "lumineon",
  "Lunatone": "lunatone",
  "Lurantis": "lurantis",
  "Luvdisc": "luvdisc",
  "Luxio": "luxio",
  "Luxray": "luxray",
  "Mabosstiff": "mabosstiff",
  "Machamp": "machamp",
  "Machoke": "machoke",
  "Machop": "machop",
  "Magby": "magby",
  "Magcargo": "magcargo",
  "Magearna": "magearna",
  "Magikarp": "magikarp",
  "Magmar": "magmar",
  "Magmortar": "magmortar",
  "Magnemite": "magnemite",
  "Magneton": "magneton",
  "Magnezone": "magnezone",
  "Makuhita": "makuhita",
  "Malamar": "malamar",
  "Mamoswine": "mamoswine",
  "Manaphy": "manaphy",
  "Mandibuzz": "mandibuzz",
  "Manectric": "manectric",
  "Manectricm": "manectric-mega",
  "Mankey": "mankey",
  "Mantine": "mantine",
  "Mantyke": "mantyke",
  "Maractus": "maractus",
  "Mareanie": "mareanie",
  "Mareep": "mareep",
  "Marill": "marill",
  "Marowak": "marowak",
  "Marshadow": "marshadow",
  "Marshtomp": "marshtomp",
  "Maschiff": "maschiff",
  "Masquerain": "masquerain",
  "Mawile": "mawile",
  "Mawilem": "mawile-mega",
  "Medicham": "medicham",
  "Medichamm": "medicham-mega",
  "Meditite": "meditite",
  "Meganium": "meganium",
  "Melmetal": "melmetal",
  "Meltan": "meltan",
  "Meowstic": "meowstic-mega",
  "Meowth": "meowth",
  "Meowthg": "meowth-galar",
  "Mesprit": "mesprit",
  "Metagross": "metagross",
  "Metang": "metang",
  "Metapod": "metapod",
  "Mew": "mew",
  "Mienfoo": "mienfoo",
  "Mienshao": "mienshao",
  "Mightyena": "mightyena",
  "Milcery": "milcery",
  "Milotic": "milotic",
  "Miltank": "miltank",
  "Mime Jr.": "mime-jr",
  "Minccino": "minccino",
  "Minun": "minun",
  "Misdreavus": "misdreavus",
  "Mismagius": "mismagius",
  "Moltres": "moltres",
  "Moltresg": "moltres-galar",
  "Monferno": "monferno",
  "Morelull": "morelull",
  "Morgrem": "morgrem",
  "Mothim": "mothim",
  "Mr. Mime": "mr-mime",
  "Mr. Mimeg": "mr-mime-galar",
  "Mr. Rime": "mr-rime",
  "Mudbray": "mudbray",
  "Mudkip": "mudkip",
  "Mudsdale": "mudsdale",
  "Muk": "muk",
  "Munchlax": "munchlax",
  "Munkidori": "munkidori",
  "Munna": "munna",
  "Murkrow": "murkrow",
  "Musharna": "musharna",
  "Nacli": "nacli",
  "Naclstack": "naclstack",
  "Naganadel": "naganadel",
  "Natu": "natu",
  "Necrozma": "necrozma",
  "Nickit": "nickit",
  "Nidoking": "nidoking",
  "Nidoqueen": "nidoqueen",
  "Nidoran♀": "nidoran-f",
  "Nidoran♂": "nidoran-m",
  "Nidorina": "nidorina",
  "Nidorino": "nidorino",
  "Nihilego": "nihilego",
  "Nincada": "nincada",
  "Ninetales": "ninetales",
  "Ninjask": "ninjask",
  "Noctowl": "noctowl",
  "Noibat": "noibat",
  "Noivern": "noivern",
  "Nosepass": "nosepass",
  "Numel": "numel",
  "Nuzleaf": "nuzleaf",
  "Nymble": "nymble",
  "Obstagoon": "obstagoon",
  "Octillery": "octillery",
  "Oddish": "oddish",
  "Ogerpon": "ogerpon",
  "Okidogi": "okidogi",
  "Omanyte": "omanyte",
  "Omastar": "omastar",
  "Onix": "onix",
  "Oranguru": "oranguru",
  "Orbeetle": "orbeetle",
  "Orthworm": "orthworm",
  "Oshawott": "oshawott",
  "Overqwil": "overqwil",
  "Pachirisu": "pachirisu",
  "Palossand": "palossand",
  "Palpitoad": "palpitoad",
  "Pancham": "pancham",
  "Pangoro": "pangoro",
  "Panpour": "panpour",
  "Pansage": "pansage",
  "Pansear": "pansear",
  "Paras": "paras",
  "Parasect": "parasect",
  "Passimian": "passimian",
  "Patrat": "patrat",
  "Pawmi": "pawmi",
  "Pawmo": "pawmo",
  "Pawmot": "pawmot",
  "Pawniard": "pawniard",
  "Pecharunt": "pecharunt",
  "Pelipper": "pelipper",
  "Perrserker": "perrserker",
  "Persian": "persian",
  "Petilil": "petilil",
  "Phanpy": "phanpy",
  "Phantump": "phantump",
  "Pheromosa": "pheromosa",
  "Phione": "phione",
  "Pichu": "pichu",
  "Pidgeot": "pidgeot",
  "Pidgeotm": "pidgeot-mega",
  "Pidgeotto": "pidgeotto",
  "Pidgey": "pidgey",
  "Pidove": "pidove",
  "Pignite": "pignite",
  "Pikachu": "pikachu",
  "Pikipek": "pikipek",
  "Piloswine": "piloswine",
  "Pincurchin": "pincurchin",
  "Pineco": "pineco",
  "Pinsir": "pinsir",
  "Pinsirm": "pinsir-mega",
  "Piplup": "piplup",
  "Plusle": "plusle",
  "Poipole": "poipole",
  "Politoed": "politoed",
  "Poliwag": "poliwag",
  "Poliwhirl": "poliwhirl",
  "Poliwrath": "poliwrath",
  "Ponyta": "ponyta",
  "Ponytag": "ponyta-galar",
  "Poochyena": "poochyena",
  "Popplio": "popplio",
  "Porygon": "porygon",
  "Porygon-Z": "porygon-z",
  "Primarina": "primarina",
  "Primeape": "primeape",
  "Prinplup": "prinplup",
  "Probopass": "probopass",
  "Psyduck": "psyduck",
  "Pupitar": "pupitar",
  "Purrloin": "purrloin",
  "Purugly": "purugly",
  "Pyroar": "pyroar",
  "Pyukumuku": "pyukumuku",
  "Quagsire": "quagsire",
  "Quaquaval": "quaquaval",
  "Quaxly": "quaxly",
  "Quaxwell": "quaxwell",
  "Quilava": "quilava",
  "Quilladin": "quilladin",
  "Qwilfish": "qwilfish",
  "Qwilfishh": "qwilfish-hisui",
  "Raboot": "raboot",
  "Rabsca": "rabsca",
  "Raichu": "raichu",
  "Raikou": "raikou",
  "Ralts": "ralts",
  "Rampardos": "rampardos",
  "Rapidash": "rapidash",
  "Rapidashg": "rapidash-galar",
  "Raticate": "raticate",
  "Rattata": "rattata",
  "Regice": "regice",
  "Regidrago": "regidrago",
  "Regieleki": "regieleki",
  "Regirock": "regirock",
  "Registeel": "registeel",
  "Relicanth": "relicanth",
  "Rellor": "rellor",
  "Remoraid": "remoraid",
  "Reuniclus": "reuniclus",
  "Revavroom": "revavroom",
  "Rhydon": "rhydon",
  "Rhyhorn": "rhyhorn",
  "Rhyperior": "rhyperior",
  "Ribombee": "ribombee",
  "Rillaboom": "rillaboom",
  "Riolu": "riolu",
  "Rockruff": "rockruff",
  "Roggenrola": "roggenrola",
  "Rolycoly": "rolycoly",
  "Rookidee": "rookidee",
  "Roselia": "roselia",
  "Roserade": "roserade",
  "Rotom": "rotom",
  "Rowlet": "rowlet",
  "Rufflet": "rufflet",
  "Runerigus": "runerigus",
  "Sableye": "sableye",
  "Sableyem": "sableye-mega",
  "Salamence": "salamence",
  "Salandit": "salandit",
  "Salazzle": "salazzle",
  "Samurott": "samurott",
  "Samurotth": "samurott-hisui",
  "Sandaconda": "sandaconda",
  "Sandile": "sandile",
  "Sandshrew": "sandshrew",
  "Sandslash": "sandslash",
  "Sandygast": "sandygast",
  "Sawk": "sawk",
  "Sawsbuck": "sawsbuck",
  "Scatterbug": "scatterbug",
  "Sceptile": "sceptile",
  "Scizor": "scizor",
  "Scizorm": "scizor-mega",
  "Scolipede": "scolipede",
  "Scorbunny": "scorbunny",
  "Scovillain": "scovillain",
  "Scrafty": "scrafty",
  "Scraggy": "scraggy",
  "Scyther": "scyther",
  "Seadra": "seadra",
  "Seaking": "seaking",
  "Sealeo": "sealeo",
  "Seedot": "seedot",
  "Seel": "seel",
  "Seismitoad": "seismitoad",
  "Sentret": "sentret",
  "Serperior": "serperior",
  "Servine": "servine",
  "Seviper": "seviper",
  "Sewaddle": "sewaddle",
  "Sharpedo": "sharpedo",
  "Sharpedom": "sharpedo-mega",
  "Shelgon": "shelgon",
  "Shellder": "shellder",
  "Shellos": "shellos",
  "Shelmet": "shelmet",
  "Shieldon": "shieldon",
  "Shiftry": "shiftry",
  "Shiinotic": "shiinotic",
  "Shinx": "shinx",
  "Shroodle": "shroodle",
  "Shroomish": "shroomish",
  "Shuckle": "shuckle",
  "Shuppet": "shuppet",
  "Sigilyph": "sigilyph",
  "Silcoon": "silcoon",
  "Silicobra": "silicobra",
  "Silvally": "silvally",
  "Simipour": "simipour",
  "Simisage": "simisage",
  "Simisear": "simisear",
  "Sinistcha": "sinistcha",
  "Sinistea": "sinistea",
  "Sirfetch’d": "sirfetchd",
  "Sizzlipede": "sizzlipede",
  "Skarmory": "skarmory",
  "Skeledirge": "skeledirge",
  "Skiddo": "skiddo",
  "Skiploom": "skiploom",
  "Skitty": "skitty",
  "Skorupi": "skorupi",
  "Skrelp": "skrelp",
  "Skuntank": "skuntank",
  "Skwovet": "skwovet",
  "Slakoth": "slakoth",
  "Sliggoo": "sliggoo",
  "Sliggooh": "sliggoo-hisui",
  "Slowbro": "slowbro",
  "Slowbrog": "slowbro-galar",
  "Slowbrom": "slowbro-mega",
  "Slowking": "slowking",
  "Slowkingg": "slowking-galar",
  "Slowpoke": "slowpoke",
  "Slowpokeg": "slowpoke-galar",
  "Slugma": "slugma",
  "Slurpuff": "slurpuff",
  "Smeargle": "smeargle",
  "Smoliv": "smoliv",
  "Smoochum": "smoochum",
  "Sneasel": "sneasel",
  "Sneaselh": "sneasel-hisui",
  "Sneasler": "sneasler",
  "Snivy": "snivy",
  "Snom": "snom",
  "Snorlax": "snorlax",
  "Snorunt": "snorunt",
  "Snover": "snover",
  "Snubbull": "snubbull",
  "Sobble": "sobble",
  "Solosis": "solosis",
  "Solrock": "solrock",
  "Spearow": "spearow",
  "Spectrier": "spectrier",
  "Spewpa": "spewpa",
  "Spheal": "spheal",
  "Spidops": "spidops",
  "Spinarak": "spinarak",
  "Spinda": "spinda",
  "Spiritomb": "spiritomb",
  "Spoink": "spoink",
  "Sprigatito": "sprigatito",
  "Spritzee": "spritzee",
  "Squirtle": "squirtle",
  "Stakataka": "stakataka",
  "Stantler": "stantler",
  "Staraptor": "staraptor",
  "Staravia": "staravia",
  "Starly": "starly",
  "Starmie": "starmie",
  "Staryu": "staryu",
  "Steelix": "steelix",
  "Steenee": "steenee",
  "Stoutland": "stoutland",
  "Stufful": "stufful",
  "Stunfisk": "stunfisk",
  "Stunfiskg": "stunfisk-galar",
  "Stunky": "stunky",
  "Sudowoodo": "sudowoodo",
  "Suicune": "suicune",
  "Sunflora": "sunflora",
  "Sunkern": "sunkern",
  "Surskit": "surskit",
  "Swablu": "swablu",
  "Swadloon": "swadloon",
  "Swalot": "swalot",
  "Swampert": "swampert",
  "Swanna": "swanna",
  "Swellow": "swellow",
  "Swinub": "swinub",
  "Swirlix": "swirlix",
  "Swoobat": "swoobat",
  "Sylveon": "sylveon",
  "Tadbulb": "tadbulb",
  "Taillow": "taillow",
  "Talonflame": "talonflame",
  "Tandemaus": "tandemaus",
  "Tangela": "tangela",
  "Tangrowth": "tangrowth",
  "Tapu Bulu": "tapu-bulu",
  "Tapu Fini": "tapu-fini",
  "Tapu Koko": "tapu-koko",
  "Tapu Lele": "tapu-lele",
  "Tarountula": "tarountula",
  "Tauros": "tauros",
  "Teddiursa": "teddiursa",
  "Tentacool": "tentacool",
  "Tentacruel": "tentacruel",
  "Tepig": "tepig",
  "Terapagos": "terapagos",
  "Terrakion": "terrakion",
  "Thievul": "thievul",
  "Throh": "throh",
  "Thundurus": "thundurus-therian",
  "Thwackey": "thwackey",
  "Timburr": "timburr",
  "Ting-Lu": "ting-lu",
  "Tinkatink": "tinkatink",
  "Tinkaton": "tinkaton",
  "Tinkatuff": "tinkatuff",
  "Tirtouga": "tirtouga",
  "Toedscool": "toedscool",
  "Toedscruel": "toedscruel",
  "Togedemaru": "togedemaru",
  "Togekiss": "togekiss",
  "Togepi": "togepi",
  "Togetic": "togetic",
  "Torchic": "torchic",
  "Torkoal": "torkoal",
  "Tornadus": "tornadus-therian",
  "Torracat": "torracat",
  "Torterra": "torterra",
  "Totodile": "totodile",
  "Toucannon": "toucannon",
  "Toxapex": "toxapex",
  "Toxel": "toxel",
  "Toxicroak": "toxicroak",
  "Tranquill": "tranquill",
  "Trapinch": "trapinch",
  "Treecko": "treecko",
  "Trevenant": "trevenant",
  "Tropius": "tropius",
  "Trubbish": "trubbish",
  "Trumbeak": "trumbeak",
  "Tsareena": "tsareena",
  "Turtonator": "turtonator",
  "Turtwig": "turtwig",
  "Tympole": "tympole",
  "Tynamo": "tynamo",
  "Type: Null": "type-null",
  "Typhlosion": "typhlosion",
  "Tyranitar": "tyranitar",
  "Tyrantrum": "tyrantrum",
  "Tyrogue": "tyrogue",
  "Tyrunt": "tyrunt",
  "Umbreon": "umbreon",
  "Unfezant": "unfezant",
  "Unown": "unown",
  "Ursaluna": "ursaluna",
  "Ursaring": "ursaring",
  "Uxie": "uxie",
  "Vanillish": "vanillish",
  "Vanillite": "vanillite",
  "Vanilluxe": "vanilluxe",
  "Vaporeon": "vaporeon",
  "Varoom": "varoom",
  "Veluza": "veluza",
  "Venipede": "venipede",
  "Venomoth": "venomoth",
  "Venonat": "venonat",
  "Venusaur": "venusaur",
  "Vespiquen": "vespiquen",
  "Vibrava": "vibrava",
  "Victini": "victini",
  "Victreebel": "victreebel",
  "Vigoroth": "vigoroth",
  "Vikavolt": "vikavolt",
  "Vileplume": "vileplume",
  "Virizion": "virizion",
  "Vivillon": "vivillon",
  "Volbeat": "volbeat",
  "Volcanion": "volcanion",
  "Volcarona": "volcarona",
  "Voltorb": "voltorb",
  "Voltorbh": "voltorb-hisui",
  "Vullaby": "vullaby",
  "Vulpix": "vulpix",
  "Wailmer": "wailmer",
  "Wailord": "wailord",
  "Walrein": "walrein",
  "Wartortle": "wartortle",
  "Watchog": "watchog",
  "Wattrel": "wattrel",
  "Weavile": "weavile",
  "Weedle": "weedle",
  "Weepinbell": "weepinbell",
  "Weezing": "weezing",
  "Weezingg": "weezing-galar",
  "Whimsicott": "whimsicott",
  "Whirlipede": "whirlipede",
  "Whiscash": "whiscash",
  "Whismur": "whismur",
  "Wigglytuff": "wigglytuff",
  "Wiglett": "wiglett",
  "Wimpod": "wimpod",
  "Wingull": "wingull",
  "Wo-Chien": "wo-chien",
  "Wobbuffet": "wobbuffet",
  "Woobat": "woobat",
  "Wooloo": "wooloo",
  "Wooper": "wooper",
  "Wugtrio": "wugtrio",
  "Wurmple": "wurmple",
  "Wynaut": "wynaut",
  "Wyrdeer": "wyrdeer",
  "Xatu": "xatu",
  "Xurkitree": "xurkitree",
  "Yamask": "yamask",
  "Yamaskg": "yamask-galar",
  "Yamper": "yamper",
  "Yanma": "yanma",
  "Yanmega": "yanmega",
  "Yungoos": "yungoos",
  "Zangoose": "zangoose",
  "Zapdos": "zapdos",
  "Zapdosg": "zapdos-galar",
  "Zarude": "zarude",
  "Zebstrika": "zebstrika",
  "Zeraora": "zeraora",
  "Zigzagoon": "zigzagoon",
  "Zigzagoong": "zigzagoon-galar",
  "Zoroark": "zoroark",
  "Zoroarkh": "zoroark-hisui",
  "Zorua": "zorua",
  "Zoruah": "zorua-hisui",
  "Zubat": "zubat",
  "Zweilous": "zweilous",
  "Zygarde": "zygarde-mega"
}

REVO_FILE = "revo12000.txt"
DATA_FILE = "random_bst_evolutions.json"

BASE_BST_OVERRIDES = {
    "wishiwashi": 175,
    "wormadam": 424,
    "wormadams": 424,
    "wormadamt": 424,
}

POKEAPI = "https://pokeapi.co/api/v2"
TOTAL_RUNS = 12000

# ====== PARTNER FORMS TO PATCH ======
TARGETS = {"wishiwashi", "wormadam", "wormadams", "wormadamt"}


def normalize_name(name: str) -> str:
    if name in NAME_ALIASES:
        return NAME_ALIASES[name]

    n = name.lower().strip()
    n = n.replace("’", "").replace("'", "")
    n = n.replace(".", "").replace(":", "")
    n = n.replace(" ", "-")
    n = re.sub(r"-+", "-", n)
    return n

def normalize_name(name: str) -> str:
    if name in NAME_ALIASES:
        return NAME_ALIASES[name]

    n = name.lower().strip()
    n = n.replace("’", "").replace("'", "")
    n = n.replace(".", "").replace(":", "")
    n = n.replace(" ", "-")
    return n

# ====== BST LOOKUP ======
@lru_cache(maxsize=None)
def get_bst(name: str) -> int:
    n = normalize_name(name)
    print(f"BST lookup: {name} → {n}")
    r = requests.get(f"{POKEAPI}/pokemon/{n}")
    if not r.ok:
        raise ValueError(f"BST lookup failed for {name}")
    data = r.json()
    return sum(s["base_stat"] for s in data["stats"])

# ====== PARSE REVO FILE ======
def parse_revo_lines():
    pattern = re.compile(r"\(([^,]+),\s*(\d+)\)")
    found = {}

    with open(REVO_FILE, "r", encoding="utf-8") as f:
        for line in f:
            if "->" not in line:
                continue

            starter, rest = line.split("->", 1)
            starter = starter.strip().lower()

            if starter not in TARGETS:
                continue

            evos = []
            for evo, count in pattern.findall(rest):
                evos.append({
                    "name": evo.strip(),
                    "count": int(count)
                })

            found[starter] = evos

    return found

# ====== PATCH LOGIC ======
def main():
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    evo_lines = parse_revo_lines()

    for starter, evos in evo_lines.items():
        print(f"Patching {starter}...")

        # ✅ Use override BST (do NOT call API)
        base_bst = BASE_BST_OVERRIDES.get(starter)
        if base_bst is None:
            raise ValueError(f"No base BST override for {starter}")

        processed = []

        for evo in evos:
            try:
                bst = get_bst(evo["name"])
            except Exception as e:
                print(f"  ❌ Skipping evo {evo['name']}: {e}")
                continue

            processed.append({
                "evolution": evo["name"],
                "bst": bst,
                "evolution_level": bst // 10,
                "probability": evo["count"] / TOTAL_RUNS
            })

        processed.sort(key=lambda x: x["bst"])

        # ✅ Now build the JSON entry
        data[starter] = {
            "base_bst": base_bst,
            "rule": "random_bst_evolution",
            "evolutions": processed
        }

        print(f"  ✔ {len(processed)} evolutions added")

    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

    print("\nPartner form patch complete.")

if __name__ == "__main__":
    main()
